spring:
  application:
    name: api-gate-way
  cloud:
    gateway:
      routes[0]:
        id: app-service
        uri: lb://app-service
        predicates[0]: Path=/api/service
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    instance-id: ${spring.application.name}:${random.int}

logging:
  level:
    root: info
    com.danielperetz: debug
