server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 3
    instance-id: ${spring.application.name}:${random.int}

spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: messaging-server

  cloud:
    config:
      fail-fast: true



